# Generated by Django 4.0.3 on 2022-04-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medturApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='clinics',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinics',
            name='open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('duration_day', models.PositiveIntegerField(default=0)),
                ('duration_night', models.PositiveIntegerField(default=0)),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medturApp.locations')),
            ],
        ),
    ]
