# Generated by Django 4.0.3 on 2022-04-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medturApp', '0003_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
