# Generated by Django 4.0.3 on 2022-04-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medturApp', '0005_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinics',
            name='close_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='open_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
