# Generated by Django 4.0.3 on 2022-04-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medturApp', '0006_alter_clinics_close_date_alter_clinics_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
