# Generated by Django 4.0.3 on 2022-04-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medturApp', '0007_alter_rates_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinics',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
